name: flutter_stripe_dev
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_functions: ^4.6.8
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  go_router: ^14.1.2
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  flutter_stripe: ^10.1.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env
